require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/buses", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Bus. As you add validations to Bus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Bus.create! valid_attributes
      get buses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bus = Bus.create! valid_attributes
      get bus_url(bus)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bus_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      bus = Bus.create! valid_attributes
      get edit_bus_url(bus)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bus" do
        expect do
          post buses_url, params: { bus: valid_attributes }
        end.to change(Bus, :count).by(1)
      end

      it "redirects to the created bus" do
        post buses_url, params: { bus: valid_attributes }
        expect(response).to redirect_to(bus_url(Bus.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bus" do
        expect do
          post buses_url, params: { bus: invalid_attributes }
        end.to change(Bus, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post buses_url, params: { bus: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested bus" do
        bus = Bus.create! valid_attributes
        patch bus_url(bus), params: { bus: new_attributes }
        bus.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bus" do
        bus = Bus.create! valid_attributes
        patch bus_url(bus), params: { bus: new_attributes }
        bus.reload
        expect(response).to redirect_to(bus_url(bus))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bus = Bus.create! valid_attributes
        patch bus_url(bus), params: { bus: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bus" do
      bus = Bus.create! valid_attributes
      expect do
        delete bus_url(bus)
      end.to change(Bus, :count).by(-1)
    end

    it "redirects to the buses list" do
      bus = Bus.create! valid_attributes
      delete bus_url(bus)
      expect(response).to redirect_to(buses_url)
    end
  end
end
